### ISSUE TITLE
添加仓库简介

### ISSUE THREAD

**Issue by Shitao5** [Guanxxxxxp/Gblog#2]
可以在 README.md 文件中写一些仓库的简介，包括博客的链接，方便别人直接从博客的仓库跳转到博客。如有需要，可以参考[我仓库介绍的源码](https://raw.githubusercontent.com/Shitao5/shitao-blog/main/README.md)和[对应的效果](https://github.com/Shitao5/shitao-blog)。

Netlify 的状态添加方法如下，供参考：

![](https://i.imgur.com/HdFNw9r.png)

**Comment by Guanxxxxxp** [comment]
噢，原来在这里能看到，之前在邮件里看见了，现在已经添加好了，辛苦学长
